package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"log"
	"os"
	"strings"
	"text/template"
)

// EnumValue holds the parsed information for a single enum entry.
type EnumValue struct {
	ConstName   string
	Code        string
	Description string
}

// TemplateData is the data structure passed to the template for execution.
type TemplateData struct {
	PackageName         string
	TypeName            string // e.g., AtlasError
	Values              []EnumValue
	UseProtonatsPackage bool // true => use protonats.<Name>, false => use unqualified names
}

func main() {
	// 1. Define and parse command-line flags
	typeFlag := flag.String("type", "", "The name of the struct type to process (e.g., errnumerAtlasError)")
	outputFlag := flag.String("output", "", "The name of the output file to generate")
	flag.Parse()

	if *typeFlag == "" || *outputFlag == "" {
		log.Fatal("Both -type and -output flags are required.")
	}

	// go generate sets the GOFILE environment variable
	inputFile := os.Getenv("GOFILE")
	if inputFile == "" {
		log.Fatal("GOFILE environment variable not set. Run this tool via 'go generate'.")
	}

	// 2. Parse the input Go source file
	fset := token.NewFileSet()
	node, err := parser.ParseFile(fset, inputFile, nil, 0)
	if err != nil {
		log.Fatalf("Failed to parse input file: %s", err)
	}

	// 3. Find and extract the error code definitions
	var values []EnumValue
	ast.Inspect(node, func(n ast.Node) bool {
		decl, ok := n.(*ast.GenDecl)
		if !ok || decl.Tok != token.VAR {
			return true // continue traversal
		}

		for _, spec := range decl.Specs {
			valueSpec, ok := spec.(*ast.ValueSpec)
			if !ok {
				continue
			}

			if len(valueSpec.Names) == 0 || len(valueSpec.Values) == 0 {
				continue
			}

			compLit, ok := valueSpec.Values[0].(*ast.CompositeLit)
			if !ok {
				continue
			}

			// More robustly check if this variable is of the target type.
			// It handles both `var v = MyType{...}` and `var v MyType = {...}`.
			var typeName string
			if valueSpec.Type != nil {
				if ident, ok := valueSpec.Type.(*ast.Ident); ok {
					typeName = ident.Name
				}
			} else if compLit.Type != nil {
				if ident, ok := compLit.Type.(*ast.Ident); ok {
					typeName = ident.Name
				}
			}

			if typeName != *typeFlag {
				continue
			}

			varName := valueSpec.Names[0].Name
			var code, description string

			if len(compLit.Elts) > 0 {
				// Check if fields are keyed (e.g., Code: "123")
				if _, ok := compLit.Elts[0].(*ast.KeyValueExpr); ok {
					for _, elt := range compLit.Elts {
						kvExpr, _ := elt.(*ast.KeyValueExpr)
						keyIdent, okKey := kvExpr.Key.(*ast.Ident)
						valueLit, okVal := kvExpr.Value.(*ast.BasicLit)
						if !okKey || !okVal || valueLit.Kind != token.STRING {
							continue
						}
						val := strings.Trim(valueLit.Value, `"`)
						if keyIdent.Name == "Code" {
							code = val
						} else if keyIdent.Name == "Description" {
							description = val
						}
					}
				} else { // Handle positional fields (e.g., {"123", "..."})
					if len(compLit.Elts) >= 2 {
						if lit, ok := compLit.Elts[0].(*ast.BasicLit); ok && lit.Kind == token.STRING {
							code = strings.Trim(lit.Value, `"`)
						}
						if lit, ok := compLit.Elts[1].(*ast.BasicLit); ok && lit.Kind == token.STRING {
							description = strings.Trim(lit.Value, `"`)
						}
					}
				}
			}

			if code != "" && description != "" {
				constName := strings.TrimPrefix(varName, "errnumer")
				values = append(values, EnumValue{
					ConstName:   constName,
					Code:        code,
					Description: description,
				})
			}
		}
		return true
	})

	if len(values) == 0 {
		log.Fatalf("No values found for type %s in file %s. Ensure variables are initialized correctly.", *typeFlag, inputFile)
	}

	// 4. Prepare data for the template
	// The generated type name is derived from the struct name, e.g., errnumerAtlasError -> AtlasError
	typeName := strings.TrimPrefix(*typeFlag, "errnumer")
	useProtonats := node.Name.Name != "protonats"
	templateData := TemplateData{
		PackageName:         node.Name.Name,
		TypeName:            typeName,
		Values:              values,
		UseProtonatsPackage: useProtonats,
	}

	// 5. Execute the template
	tmpl, err := template.New("enum").Parse(codeTemplate)
	if err != nil {
		log.Fatalf("Failed to parse template: %s", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, templateData); err != nil {
		log.Fatalf("Failed to execute template: %s", err)
	}

	// 6. Format the generated code
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		log.Fatalf("Failed to format generated code: %s", err)
	}

	// 7. Write the formatted code to the output file
	err = os.WriteFile(*outputFlag, formatted, 0644)
	if err != nil {
		log.Fatalf("Failed to write output file: %s", err)
	}

	fmt.Printf("Successfully generated %s\n", *outputFlag)
}

// The Go code template for the generated file.
const codeTemplate = `// Code generated by errnumer; DO NOT EDIT.

package {{.PackageName}}

{{- if .UseProtonatsPackage}}
import "xiam.li/protonats/go/protonats"
{{- end}}

type {{.TypeName}} int

const (
{{- range $i, $val := .Values}}
{{- if eq $i 0}}
 {{$val.ConstName}} {{$.TypeName}} = iota
{{- else}}
 {{$val.ConstName}}
{{- end}}
{{- end}}
)

var {{.TypeName}}Codes = []string{
{{- range .Values}}
 "{{.Code}}",
{{- end}}
}

var {{.TypeName}}Descriptions = []string{
{{- range .Values}}
  "{{.Description}}",
{{- end}}
}

// AsServerError converts the enum to a protonats.ServerError.
func (e {{.TypeName}}) AsServerError() {{if .UseProtonatsPackage}}protonats.ServerError{{else}}ServerError{{end}} {
	codeString := {{.TypeName}}Codes[e]
	description := {{.TypeName}}Descriptions[e]
	{{- if .UseProtonatsPackage}}
	return protonats.NewServerErr(codeString, description)
	{{- else}}
	return NewServerErr(codeString, description)
	{{- end}}
}

// String returns the human-readable description of the error.
func (e {{.TypeName}}) String() string {
	if e < 0 || int(e) >= len({{.TypeName}}Descriptions) {
		return {{.TypeName}}Descriptions[0] // Default to the 'Unknown' error
	}
	return {{.TypeName}}Descriptions[e]
}

// Code returns the error code string of the error.
func (e {{.TypeName}}) Code() string {
	if e < 0 || int(e) >= len({{.TypeName}}Codes) {
		return {{.TypeName}}Codes[0] // Default to the 'Unknown' error code
	}
	return {{.TypeName}}Codes[e]
}

// {{.TypeName}}Values returns a slice of all possible values for the enum.
func {{.TypeName}}Values() []{{.TypeName}} {
	return []{{.TypeName}}{
	{{- range .Values}}
	 {{.ConstName}},
	{{- end}}
	}
}

// {{.TypeName}}FromCode returns the value for the given error code.
func {{.TypeName}}FromCode(s string) ({{.TypeName}}, bool) {
	for i, code := range {{.TypeName}}Codes {
		if code == s {
			return {{.TypeName}}(i), true
		}
	}
	// Return the first enum value (typically the 'Unknown' error) by default.
	return {{.TypeName}}(0), false
}

// {{.TypeName}}From extracts the {{.TypeName}} from a ProtoNATS service error, if possible.
func {{.TypeName}}From(err error) ({{.TypeName}}, bool) {
	{{- if .UseProtonatsPackage}}
	if srvErr, ok := protonats.AsServiceError(err); ok {
		return {{.TypeName}}FromCode(srvErr.Code)
	}
	{{- else}}
	if srvErr, ok := AsServiceError(err); ok {
		return {{.TypeName}}FromCode(srvErr.Code)
	}
	{{- end}}
	return {{.TypeName}}(0), false
}
`
